version: '3.8'

services:
  backend:
    build: ./backend/app
    ports:
      - "8000:80"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
